# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-23 23:25
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.CharField(default='', max_length=20, verbose_name='\u4f5c\u8005')),
                ('chickRate', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u7387')),
                ('overView', models.TextField(default='', verbose_name='\u6587\u7ae0\u6982\u8ff0')),
                ('garTitle', models.CharField(default='', max_length=100, verbose_name='\u6bb5\u843d\u6807\u9898')),
                ('garagraph', DjangoUeditor.models.UEditorField(default='', verbose_name='\u6bb5\u843d\u6587\u7ae0')),
                ('passed', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838\u901a\u8fc7')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u64b0\u5199',
                'verbose_name_plural': '\u6587\u7ae0\u64b0\u5199',
            },
        ),
        migrations.CreateModel(
            name='HeadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', '\u4e3b\u9875'), ('archive', '\u5b58\u6863'), ('tags', '\u6807\u7b7e'), ('about', '\u5173\u4e8e'), ('friends', '\u670b\u53cb\u5708')], max_length=10, verbose_name='\u53d1\u5e03\u9875\u9762')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u9875\u5934\u5185\u5bb9')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9875\u5934\u4fe1\u606f',
                'verbose_name_plural': '\u9875\u5934\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='pageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('about', '\u5173\u4e8e'), ('friends', '\u670b\u53cb\u5708')], max_length=10, verbose_name='\u53d1\u5e03\u9875\u9762')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9875\u9762\u5185\u5bb9',
                'verbose_name_plural': '\u9875\u9762\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
                ('tag_2', models.CharField(default='', max_length=50, verbose_name='\u989d\u5916\u6807\u7b7e')),
                ('tag_3', models.CharField(default='', max_length=50, verbose_name='\u5176\u4ed6\u6807\u7b7e')),
                ('chickRate', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u7387')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e\u7ba1\u7406',
                'verbose_name_plural': '\u6807\u7b7e\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Tags', verbose_name='\u6587\u7ae0\u6807\u7b7e'),
        ),
        migrations.CreateModel(
            name='PassArticle',
            fields=[
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u5ba1\u6838',
                'proxy': True,
                'verbose_name_plural': '\u6587\u7ae0\u5ba1\u6838',
            },
            bases=('article.article',),
        ),
        migrations.CreateModel(
            name='PassedArticle',
            fields=[
            ],
            options={
                'verbose_name': '\u5df2\u5ba1\u6838\u6587\u7ae0',
                'proxy': True,
                'verbose_name_plural': '\u5df2\u5ba1\u6838\u6587\u7ae0',
            },
            bases=('article.article',),
        ),
    ]
