# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('tags', models.CharField(default='', max_length=50, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.CharField(default='', max_length=20, verbose_name='\u4f5c\u8005')),
                ('chickRate', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u7387')),
                ('garTitle', models.CharField(default='', max_length=100, verbose_name='\u6bb5\u843d\u6807\u9898')),
                ('garagraph', models.TextField(verbose_name='\u6bb5\u843d\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='HeadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', '\u4e3b\u9875'), ('archive', '\u5b58\u6863'), ('tags', '\u6807\u7b7e'), ('about', '\u5173\u4e8e'), ('friends', '\u670b\u53cb\u5708')], max_length=10, verbose_name='\u53d1\u5e03\u9875\u9762')),
                ('content', models.TextField(verbose_name='\u9875\u5934\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u9875\u5934\u4fe1\u606f',
                'verbose_name_plural': '\u9875\u5934\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='pageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('about', '\u5173\u4e8e'), ('friends', '\u670b\u53cb\u5708')], max_length=10, verbose_name='\u53d1\u5e03\u9875\u9762')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u9875\u9762\u5185\u5bb9',
                'verbose_name_plural': '\u9875\u9762\u5185\u5bb9',
            },
        ),
    ]
