# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='amount',
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Column', verbose_name='\u6587\u7ae0\u4e13\u680f'),
        ),
    ]
