# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_headinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
