# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_pageinfo_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u53d1\u8868\u6587\u7ae0', 'verbose_name_plural': '\u53d1\u8868\u6587\u7ae0'},
        ),
        migrations.AddField(
            model_name='article',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838\u901a\u8fc7'),
        ),
    ]
