# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170811_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_2',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='\u989d\u5916\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_3',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='\u5176\u4ed6\u6807\u7b7e'),
        ),
    ]
