# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170219_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='overView',
            field=models.TextField(default='', verbose_name='\u6587\u7ae0\u6982\u8ff0'),
        ),
    ]
