# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170811_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassArticle',
        ),
        migrations.DeleteModel(
            name='PassedArticle',
        ),
        migrations.RemoveField(
            model_name='article',
            name='column',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag_2',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag_3',
        ),
        migrations.AddField(
            model_name='column',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='\u6587\u7ae0id'),
        ),
        migrations.AddField(
            model_name='tags',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='\u6587\u7ae0id'),
        ),
    ]
