# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4')),
            ],
        ),
    ]
