# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170922_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Column', verbose_name='\u6240\u5c5e\u4e13\u680f'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='\u6587\u7ae0id'),
        ),
    ]
