# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170219_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='chickRate',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u7387'),
        ),
    ]
