# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_tags_chickrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_2',
            field=models.CharField(default='', max_length=50, verbose_name='\u989d\u5916\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_3',
            field=models.CharField(default='', max_length=50, verbose_name='\u5176\u4ed6\u6807\u7b7e'),
        ),
    ]
